name: Build

on:
  push:
    branches: [asus_n]
  #workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Env cache (restore)
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: env-cache-${{ github.sha }}
          restore-keys: env-cache-

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          sudo ln -sf /usr/bin/bash /usr/bin/sh
          echo `pwd`/toolchain/Python-2.7.18 >> $GITHUB_PATH

      - name: Build
        run: bash ./build.sh lenovo89_tb_x10_jb2
        env:
          MAKEJOBS: "-j5"

      - name: Git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add ./build_result
            git commit -m "Build"
            git push
          fi

      - name: Env cache (save)
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v4
        with:
          path: ./
          key: env-cache-${{ github.sha }}
