name: Build

on:
  push:
    branches: [asus_n]
  #workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          sudo apt install python2
          sudo rm /usr/bin/sh
          sudo touch /usr/bin/sh
          sudo chmod 777 /usr/bin/sh
          cat << EOL > /usr/bin/sh
          #!/bin/bash
          bash -c "$@"
          RET=$?
          if [ $RET -ne "0" ]; then
            echo "`date '+[%Y-%m-%d %T.%N]'` $@" >> /tmp/errors
          fi
          exit $RET
          EOL
          sudo chmod 755 /usr/bin/sh
          date "+Time zone is %Z (UTC%:::z)" > /tmp/errors
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Build
        run: bash ./build.sh lenovo89_tb_x10_jb2
        env:
          MAKEJOBS: "-j5"

      - name: Git
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add ./build_result
            git commit -m "Build"
            git push
          fi

      - name: Post scripts
        if: ${{ always() }}
        run: |
          cat /tmp/errors
